services:
  - type: web
    name: pdf-ocr-app
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=10000 --server.enableCORS=false"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
